### PR TITLE
fix domain notification event listeners configuration via API

### LINKED ISSUE #147: Domain notification event listeners not setup when a domain is configured using the api
When a domain is configured on the notification service using the /domains api, the event listeners are not setup and because of this, it does not listen to events. 

However, when the service is restarted, the event listeners are setup and can now listen to events. 

Steps to Reproduce:

1. Configure a new domain on the notification service

````
POST /domains HTTP/1.1
Host: localhost:15554
Authorization: Bearer <token>
Content-Type: application/json
Cookie: JSESSIONID=97D5C32F3FB98FC44434D7E9BF70CCB1

[
    {
        "domainId": "test1",
        "profiles": [
            {
                "profileId": "default",
                "rules": [
                    {
                        "expression": "true",
                        "provider": "none",
                        "priority": 1000
                    }
                ]
            }
        ],
        "providerConfigurations": [],
        "userNotificationMessages": [
            {
                "type": "email",
                "eventTriggers": [
                    "user.password.reset.initiation"
                ],
                "messageTemplate": "user.password.reset.initiation.template"
            },
            {
                "type": "email",
                "eventTriggers": [
                    "user.validation.property.email"
                ],
                "messageTemplate": "user.validation.property.email.template",
                "destinationProperty": "propertyName"
            },
            {
                "type": "sms",
                "eventTriggers": [
                    "user.validation.property.sms"
                ],
                "messageTemplate": "user.validation.property.sms.template",
                "destinationProperty": "propertyName"
            }
        ],
        "eventNotificationMessages": []
    }
]
````

2. Check RabbitMQ for queue creation.

http://localhost:15672/#/queues

Expected: Two queues are supposed to be created for the domain: UserEventQueue[test1.event.#] and UserEventQueue[test1.user.#]. This shows that the service has started  listening to user and generic events. Notification service should listen for events as soon as a domain is configured as above or by creating a domainConfiguration item using the `POST /repo/domainConfigurations` api.

Actual: These queues are not created. However, when the service is restarted, the queues are created and the service listens for events.

### PR DESCRIPTION
**Pull request by IEnoobong**
closes #147

### CODE REVIEW

File: mmadu-notifications/src/main/java/com/mmadu/notifications/service/populator/DomainPopulator.java [hunk 1]
```diff
@@ -82,6 +97,7 @@ private void doInitializeDomains(List<DomainNotificationConfigurationList.Domain
     private void initializeDomain(DomainNotificationConfigurationList.DomainItem domainItem) {
         DomainNotificationConfiguration configuration = domainItem.toEntity();
         domainNotificationConfigurationRepository.save(configuration);
+        applicationEventPublisher.publishEvent(new DomainInitializedEvent(configuration.getDomainId()));
```
Comment (geraldoyudo) [inline mmadu-notifications/src/main/java/com/mmadu/notifications/service/populator/DomainPopulator.java]: fire this event when everything has been saved. So it should be the last in this method.

**Review by geraldoyudo — CHANGES_REQUESTED** [review]
